name: notesme
description: "NotesMe — simple notes app with room to grow."
publish_to: 'none'

# Sesuaikan dengan versi Flutter/Dart lo. Aman untuk Flutter 3.22+ (Dart 3.4+).
environment:
  sdk: '>=3.4.0 <4.0.0'

version: 0.1.0+1

dependencies:
  flutter:
    sdk: flutter

  # Routing modern
  go_router: ^16.0.0

  # Secrets/config (.env)
  flutter_dotenv: ^5.1.0

  # (opsional nanti) state mgmt, storage, dsb
  # hive: ^2.2.3
  # hive_flutter: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  assets:
    # siapkan folder aset umum (ikon, ilustrasi)
    - assets/
    - assets/icons/
    # allow load env default (.env) — nanti kita load di main.dart
    - .env
